#  NOTE:───────────────────────────────────────────────────────────────────────┐
#  │                                                                           │
#  │ FOLLOW EDLLT's INSTRUCTIONS TO DISABLE PHANTOM KILLER                     │
#  │                                                                           │
#  │ in adb shell:                                                             │
#  │   - adb shell "/system/bin/device_config set_sync_disabled_for_tests persistent"
#  │   - adb shell "/system/bin/device_config put activity_manager max_phantom_processes 2147483647"
#  │   - adb shell settings put global settings_enable_monitor_phantom_procs false
#  │                                                                           │
#  │                                                                           │
#  │ FOLLOW LinuxDroidMaster's INSTRUCTIONS TO INSTALL ARCHLINUX               │
#  │                                                                           │
#  │ in Termux:                                                                │
#  │   - pkg update && pkg install x11-repo                                    │
#  │   - pkg install termux-x11-nightly pulseaudio proot-distro                │
#  │   - wget https://raw.githubusercontent.com/LinuxDroidMaster/Termux-Desktops/main/scripts/proot_arch/startxfce4_arch.sh
#  │   - chmod +x startxfce4_arch.sh                                           │
#  │   - proot-distro install archlinux                                        │
#  │   - proot-distro login archlinux                                          │
#  │                                                                           │
#  │ in archlinux proot:                                                       │
#  │   - pacman -Syu                                                           │
#  │   - pacman -S sudo xfce4 xfce4-goodies pulseaudio pulseaudio-alsa         │
#  │   - ln -sf /usr/share/zoneinfo/Etc/GMT... /etc/localtime  # YOUR TIMEZONE │
#  │   - useradd -m -G wheel droidmaster                                       │
#  │   - passwd droidmaster                                                    │
#  │   - nano /etc/sudoers                                                     │
#  │                                                                           │
#  │ in /etc/sudoers:                                                          │
#  │   - # Paste the following line                                            │
#  │   - droidmaster ALL=(ALL) ALL                                             │
#  │                                                                           │
#  │                                                                           │
#  │ FOLLOW LinuxDroidMaster's INSTRUCTIONS TO START ARCHLINUX                 │
#  │                                                                           │
#  │ in Termux:                                                                │
#  │   - # CLI SESSION                                                         │
#  │   - proot-distro login archlinux --user droidmaster --shared-tmp          │
#  │   - # Xfce4 DESKTOP                                                       │
#  │   - ./startxfce4_arch.sh                                                  │
#  │                                                                           │
#  └───────────────────────────────────────────────────────────────────────────┘

# ┌─────────┐
# │ General │
# └─────────┘

# Allow external applications to execute arbitrary commands within Termux.
allow-external-apps = true

# Default working directory that will be used when launching the app.
# default-working-directory = /data/data/com.termux/files/home

# Uncomment to disable toasts shown on terminal session change.
# disable-terminal-session-change-toast = true

# Uncomment to not show soft keyboard on application start.
# hide-soft-keyboard-on-startup = true

# Uncomment to let keyboard toggle button to enable or disable software keyboard instead of showing/hiding it.
# soft-keyboard-toggle-behaviour = enable/disable

# Adjust terminal scrollback buffer. Max is 50000. May have negative impact on performance.
# terminal-transcript-rows = 2000

# Uncomment to use volume keys for adjusting volume and not for the extra keys functionality.
# volume-keys = volume

# ┌─────────────────┐
# │ Fullscreen mode │
# └─────────────────┘

# Uncomment to let Termux start in full screen mode.
fullscreen = true

# Uncomment to attempt workaround layout issues when running in full screen mode.
# use-fullscreen-workaround = true

# ┌────────┐
# │ Cursor │
# └────────┘

# Cursor blink rate. Values 0, 100 - 2000.
# terminal-cursor-blink-rate = 0

# Cursor style: block, bar, underline.
# terminal-cursor-style = block

# ┌────────────┐
# │ Extra keys │
# └────────────┘

# Settings for choosing which set of symbols to use for illustrating keys. (default, arrows-only, arrows-all, all and none)
extra-keys-style = all

# Force capitalize all text in extra keys row button labels.
# extra-keys-text-all-caps = true

#  NOTE: Extra-key configuration

extra-keys = [[{key: "ESC", display: "⎋"}, {key: "TAB", display: "↹"}, {key: "CTRL", display: "⌘"}, {key: "ALT", display: "⌥"}, {key: "SHIFT", display: "⊹"}, {key: "LEFT", display: "←"}, {key: "DOWN", display: "↓"}, {key: "UP", display: "↑"}, {key: "RIGHT", display: "→"}]]

#  NOTE: Extra-key configuration (for termux-x11)

# [[{key: "ESC", display: "⎋"}, {key: "TAB", display: "↹"}, {key: "CTRL", display: "⌘"}, {key: "META", display: "⎚"}, {key: "ALT", display: "⌥"}, {key: "SHIFT", display: "⊹"}, {key: "ENTER", display: "⬖"}, {key: "LEFT", display: "←"}, {key: "DOWN", display: "↓"}, {key: "UP", display: "↑"}, {key: "RIGHT", display: "→"}]]

# ┌───────────────┐
# │ Colors/themes │
# └───────────────┘

# Force black colors for drawer and dialogs
# use-black-ui = true

# ┌───────────────────────┐
# │ HW keyboard shortcuts │
# └───────────────────────┘

# Disable hardware keyboard shortcuts.
# disable-hardware-keyboard-shortcuts = true

# Open a new terminal with ctrl + t (volume down + t)
# shortcut.create-session = ctrl + t

# Go one session down with (for example) ctrl + 2
# shortcut.next-session = ctrl + 2

# Go one session up with (for example) ctrl + 1
# shortcut.previous-session = ctrl + 1

# Rename a session with (for example) ctrl + n
# shortcut.rename-session = ctrl + n

# ┌──────────┐
# │ Bell key │
# └──────────┘

# Vibrate device (default).
# bell-character = vibrate

# Beep with a sound.
# bell-character = beep

# Ignore bell character.
# bell-character = ignore

# ┌──────────┐
# │ Back key │
# └──────────┘

# Send the Escape key.
back-key=escape

# Hide keyboard or leave app (default).
# back-key=back

# ┌────────────────────────────┐
# │ Keyboard issue workarounds │
# └────────────────────────────┘

# Letters might not appear until enter is pressed on Samsung devices
# enforce-char-based-input = true

# ctrl+space (for marking text in emacs) does not work on some devices
# ctrl-space-workaround = true
